apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - port: {{ .Values.deployment.app.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.deployment.app.containerPort }}
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
  
  
  
  
  
  