apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  {{- $path :=  .Values.configMap.kubeEnv }}
    {{ (.Files.Glob $path).AsConfig | indent 2 }}